#!/bin/sh
echo SIGTOKEN=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 8) >secrets
echo SIGKEY1=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64) >>secrets
echo SIGKEY2=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64) >>secrets
echo SIGKEY3=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64) >>secrets
echo SIGKEY4=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64) >>secrets
