#!/bin/sh
/bin/makedevs /dev/null c 1 3 0 0 s
/bin/makedevs /dev/zero c 1 5 0 0 s
/bin/makedevs /dev/tty c 5 0 0 0 s
/bin/makedevs /dev/console c 5 1 0 0 s
/bin/makedevs /dev/tty c 4 1 1 9
exec /bin/init
